// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sensor_reading.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSensorReading = `-- name: CreateSensorReading :one
INSERT INTO sensor_readings (sensor_id, temperature, humidity, pressure)
VALUES ($1, $2, $3, $4 )
RETURNING reading_timestamp, sensor_id, temperature, humidity, pressure
`

type CreateSensorReadingParams struct {
	SensorID    pgtype.Int4   `json:"sensor_id"`
	Temperature pgtype.Float8 `json:"temperature"`
	Humidity    pgtype.Float8 `json:"humidity"`
	Pressure    pgtype.Float8 `json:"pressure"`
}

func (q *Queries) CreateSensorReading(ctx context.Context, arg CreateSensorReadingParams) (SensorReading, error) {
	row := q.db.QueryRow(ctx, createSensorReading,
		arg.SensorID,
		arg.Temperature,
		arg.Humidity,
		arg.Pressure,
	)
	var i SensorReading
	err := row.Scan(
		&i.ReadingTimestamp,
		&i.SensorID,
		&i.Temperature,
		&i.Humidity,
		&i.Pressure,
	)
	return i, err
}

const getSensorReadingDaily = `-- name: GetSensorReadingDaily :many
SELECT day, sensor_id, min_temperature, avg_temperature, max_temperature, min_humidity, avg_humidity, max_humidity 
FROM sensor_readings_daily
LIMIT $1 OFFSET $2
`

type GetSensorReadingDailyParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSensorReadingDaily(ctx context.Context, arg GetSensorReadingDailyParams) ([]SensorReadingsDaily, error) {
	rows, err := q.db.Query(ctx, getSensorReadingDaily, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReadingsDaily
	for rows.Next() {
		var i SensorReadingsDaily
		if err := rows.Scan(
			&i.Day,
			&i.SensorID,
			&i.MinTemperature,
			&i.AvgTemperature,
			&i.MaxTemperature,
			&i.MinHumidity,
			&i.AvgHumidity,
			&i.MaxHumidity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSensorReadingHourly = `-- name: GetSensorReadingHourly :many
SELECT hour, sensor_id, min_temperature, avg_temperature, max_temperature, min_humidity, avg_humidity, max_humidity 
FROM sensor_readings_hourly
LIMIT $1 OFFSET $2
`

type GetSensorReadingHourlyParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSensorReadingHourly(ctx context.Context, arg GetSensorReadingHourlyParams) ([]SensorReadingsHourly, error) {
	rows, err := q.db.Query(ctx, getSensorReadingHourly, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReadingsHourly
	for rows.Next() {
		var i SensorReadingsHourly
		if err := rows.Scan(
			&i.Hour,
			&i.SensorID,
			&i.MinTemperature,
			&i.AvgTemperature,
			&i.MaxTemperature,
			&i.MinHumidity,
			&i.AvgHumidity,
			&i.MaxHumidity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSensorReadingMinutes = `-- name: GetSensorReadingMinutes :many
SELECT minute, sensor_id, min_temperature, avg_temperature, max_temperature, min_humidity, avg_humidity, max_humidity 
FROM sensor_readings_minutes
LIMIT $1 OFFSET $2
`

type GetSensorReadingMinutesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSensorReadingMinutes(ctx context.Context, arg GetSensorReadingMinutesParams) ([]SensorReadingsMinute, error) {
	rows, err := q.db.Query(ctx, getSensorReadingMinutes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorReadingsMinute
	for rows.Next() {
		var i SensorReadingsMinute
		if err := rows.Scan(
			&i.Minute,
			&i.SensorID,
			&i.MinTemperature,
			&i.AvgTemperature,
			&i.MaxTemperature,
			&i.MinHumidity,
			&i.AvgHumidity,
			&i.MaxHumidity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
